{
 "title": "Home Elec Report",
 "description": "Linky datas",
 "time": { "from": "2025-10-21T07:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Live-Conso",
   "type": "timeseries",
   "description": "Live conso",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "dataset": "mylinky",
     "rawSql": "SELECT\r\n  utc AS \"time\",\r\n  PAPP\r\nFROM stream\r\nWHERE\r\n  $__timeFilter(utc)\r\nORDER BY utc"
    }
   ]
  },
  {
   "title": "Compteur",
   "type": "gauge",
   "description": "Compteur HC HP",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "dataset": "mylinky",
     "rawSql": "SELECT\r\n  utc AS \"time\",\r\n  HCHC,HCHP\r\nFROM stream\r\nWHERE\r\n  $__timeFilter(utc)\r\nORDER BY utc"
    }
   ]
  },
  {
   "title": "Heures Creuses",
   "type": "gauge",
   "description": "Compteur HC/Prix",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "dataset": "mylinky",
     "rawSql": "SELECT\r\n  utc AS \"time\",\r\n  HCHC\r\nFROM mylinky.stream\r\nWHERE\r\n  $__timeFilter(utc)\r\nORDER BY utc"
    }
   ]
  },
  {
   "title": "Heures Pleines",
   "type": "gauge",
   "description": "Compteur HP/Prix",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "dataset": "mylinky",
     "rawSql": "SELECT\r\n  utc AS \"time\",\r\n  HCHP\r\nFROM mylinky.stream\r\nWHERE\r\n  $__timeFilter(utc)\r\nORDER BY utc"
    }
   ]
  }
 ]
}